config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :admin do
    resources :services do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :catalogs do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'

  # KepplerBlog route engine
  mount KepplerBlog::Engine, :at => '/', as: 'blog'

  # KepplerContactUs route engine
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'
end

app/models/service.rb
# Service Model
class Service < ActiveRecord::Base
  include ElasticSearchable
  include ActivityHistory

  def self.query(query)
    { query: { multi_match: {
      query: query,
      fields: [:tittle, :body],
      operator: :and,
      lenient: true }
    }, sort: { id: 'desc' }, size: count }
  end

  # Build index elasticsearch
  def as_indexed_json(_options = {})
    as_json(
      only: [:id, :tittle, :body]
    )
  end
end

app/controllers/admin/services_controller.rb
module Admin
  # ServicesController
  class ServicesController < AdminController
    before_action :set_service, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /services
    def index
      services = Service.searching(@query).all
      @objects = services.page(@current_page)
      @total = services.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to services_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    # GET /services/1
    def show
    end

    # GET /services/new
    def new
      @service = Service.new
    end

    # GET /services/1/edit
    def edit
    end

    # POST /services
    def create
      @service = Service.new(service_params)

      if @service.save
        redirect(@service, params)
      else
        render :new
      end
    end

    # PATCH/PUT /services/1
    def update
      if @service.update(service_params)
        redirect(@service, params)
      else
        render :edit
      end
    end

    # DELETE /services/1
    def destroy
      @service.destroy
      redirect_to admin_services_path, notice: actions_messages(@service)
    end

    def destroy_multiple
      Service.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_services_path(page: @current_page, search: @query),
        notice: actions_messages(Service.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:tittle, :body)
    end

    def show_history
      get_history(Service)
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.reorder.css_class('md-light')
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: 'height: {{windowHeight}}px;' }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t('keppler.titles.history')
			- @activities.each do |activity|
				- if activity.trackable_type.eql? 'Session'
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }

app/views/admin/services/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_services_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @service] do |f|
						.row
							= f.input :tittle
							= f.input :body, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'mini'} }

							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: '_save'
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: '_add_other'

app/views/admin/services/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Service
			= link_to edit_admin_service_path(@service), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit"), "data-no-turbolink" => true  do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.reorder.css_class("md-light")
		= t("keppler.models.singularize.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.service.tittle")
				.display-value= @service.tittle
			%li.list-row
				.display-label= t("activerecord.attributes.service.body")
				.display-value= @service.body.html_safe
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_services_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/services/_listing.html.haml
%tr{ id: "row-#{service.id}" }
	- if can? :destroy_multiple, Service
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_service_path(service), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{service.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{service.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{service.id}" }

		%td{style:"width: 30%"}
			= link_to "", admin_service_path(service, search: @query), remote: true, class: "show-row"
			%span
				= service.tittle
	%td{style:"width: 5%"}
		= link_to admin_service_path(service), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/services/edit.html.haml
= title(t('keppler.titles.edit', model: "Services"))
= render 'form'

app/views/admin/services/index.html.haml
= title(t('keppler.titles.index', model: "Services"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_service_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only", "data-no-turbolink" => true  do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |service|
				= render 'listing', service: service
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.services"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_service_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/services/new.html.haml
= title(t('keppler.titles.new', model: "Services"))
= render 'form'

app/views/admin/services/show.html.haml
= title(t('keppler.titles.show', model: "Services"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Service
				= link_to admin_service_path(@service), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Service
				= link_to edit_admin_service_path(@service), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_services_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
						.display-value.fs-body-1.tc-black-2= @service.id
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.tittle")
						.display-value.fs-body-1.tc-black-2= @service.tittle
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.body")
						.display-value.fs-body-1.tc-black-2= @service.body.html_safe

app/views/admin/services/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@service.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");